NOME = "[Casa de Leilões] "

welcome = NOME + "Bem vindo!"  
opcoesVendedor = NOME + "Olá vendedor! Digite um dos números abaixo para acessar a opção correspondente:\n 1 - Iniciar leilão\n 2 - Finalizar leilão\n 3 - Listar meus produtos\n 4 - Sair"
opcoesComprador = NOME + "Olá Comprador! Digite um dos números abaixo para acessar a opção correspondente:\n 1 - Listar os artigos abertos\n 2 - Fazer um lance\n 3 - Sair\n"
start_auction = NOME + "Informe a descrição e valor inicial (lance mínimo) do artigo." 
end_auction = NOME + "Informe o ID do produto para encerrar o leilão: " 
artigo_lance = NOME + "Informe o ID do artigo: "
valor_lance = NOME + "Informe o valor do lance: "
vendedor_opcao2 = NOME + ""
